services:

  database:
    image: postgres:16.0-alpine
    restart: always
    environment:
      POSTGRES_DB: sandbox
      POSTGRES_USER: gabbloquet
      POSTGRES_PASSWORD: p@ssw0rd
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '8900:8900'
    volumes:
      - 'minio-data:/data/minio'
    environment:
      - "MINIO_ACCESS_KEY=sandboxkey"
      - "MINIO_SECRET_KEY=sandboxsecret"
    command: server /data/minio --console-address ":8900"

volumes:
  db-data:
  minio-data: