services:

  database:
    image: postgres:16.0-alpine
    restart: always
    environment:
      POSTGRES_DB: sandbox
      POSTGRES_USER: gabbloquet
      POSTGRES_PASSWORD: p@ssw0rd
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: