spring:
  application:
    name: test-containers-sandbox
  datasource:
      url: jdbc:postgresql://localhost:5432/sandbox
      username: gabbloquet
      password: p@ssw0rd
  flyway:
    table: schema_version
  jpa:
    hibernate:
      ddl-auto: validate

bucket:
  name: "sandbox-files"
  endpoint: "http://localhost:9000"
  access-key: sandboxkey
  secret-key: sandboxsecret